export const FETCH_BLOGS = "FETCH_BLOGS";
export const FETCH_BLOGS_PENDING = 'FETCH_BLOGS_PENDING';
export const FETCH_BLOGS_FULFILLED = 'FETCH_BLOGS_FULFILLED';
export const FETCH_BLOGS_REJECTED = 'FETCH_BLOGS_REJECTED';