export const FETCH_SINGLE_POST = "FETCH_SINGLE_POST";
export const FETCH_SINGLE_POST_PENDING = 'FETCH_SINGLE_POST_PENDING';
export const FETCH_SINGLE_POST_FULFILLED = 'FETCH_SINGLE_POST_FULFILLED';
export const FETCH_SINGLE_POST_REJECTED = 'FETCH_SINGLE_POST_REJECTED';