export const FETCH_SINGLE_BLOG = "FETCH_SINGLE_BLOG";
export const FETCH_SINGLE_BLOG_PENDING = 'FETCH_SINGLE_BLOG_PENDING';
export const FETCH_SINGLE_BLOG_FULFILLED = 'FETCH_SINGLE_BLOG_FULFILLED';
export const FETCH_SINGLE_BLOG_REJECTED = 'FETCH_SINGLE_BLOG_REJECTED';